// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Infrastructure;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(Customer360DbContext))]
    partial class Customer360DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasJsonPropertyName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasJsonPropertyName("action");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasJsonPropertyName("customerId");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasJsonPropertyName("customerName");

                    b.Property<string>("CustomerType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasJsonPropertyName("customerType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("description");

                    b.Property<string>("Field")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("field");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasJsonPropertyName("status");

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("timestamp");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("user");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("backend.Models.FieldConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiField")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasJsonPropertyName("apiField");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasJsonPropertyName("displayLabel");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("displayOrder");

                    b.Property<string>("MaskingRule")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasJsonPropertyName("maskingRule");

                    b.Property<string>("ProfileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasJsonPropertyName("profileType");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasJsonPropertyName("section");

                    b.Property<bool>("Sensitive")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("sensitive");

                    b.Property<bool>("Visible")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("visible");

                    b.Property<int>("VisibleCharCount")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("visibleCharCount");

                    b.HasKey("Id");

                    b.HasIndex("ProfileType", "ApiField")
                        .IsUnique();

                    b.ToTable("field_configs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
